author: <a href="https://github.com/mathieuboudreau">Mathieu Boudreau</a>
bibtex_bibfiles:
- ../paper.bib
copyright: '2023'
exclude_patterns:
- _build
- Thumbs.db
- .DS_Store
- '**.ipynb_checkpoints'
execute:
  execute_notebooks: auto
html:
  comments:
    hypothesis: true
  extra_navbar: Return to <a href="https://neurolibre.org/">NeuroLibre</a>
  favicon: images/favicon.ico
  home_page_in_navbar: true
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
launch_buttons:
  binderhub_url: https://binder-mcgill.conp.cloud
  notebook_interface: jupyterlab
only_build_toc_files: true
parse:
  myst_enable_extensions:
  - html_image
  - amsmath
  - colon_fence
  - deflist
  - dollarmath
  - html_admonition
  - html_image
  - linkify
  - replacements
  - smartquotes
  - substitution
repository:
  path_to_book: content/
  url: https://github.com/roboneurolibre/t1-book-neurolibre
sphinx:
  config:
    bibtex_default_style: plain
    bibtex_reference_style: author_year
    bibtex_tooltips: true
    html_context:
      default_mode: light
    html_css_files:
    - custom.css
    html_static_path:
    - _static
    html_theme_options:
      logo:
        image_dark: https://github.com/agahkarakuzu/figserver/blob/main/logo_dark2.png?raw=true
        image_light: https://github.com/agahkarakuzu/figserver/blob/main/logo_light.png?raw=true
  local_extensions: null
  recursive_update: true
title: Quantitative T1 MRI
